spring.application.name=CarRentalEurekaServer
server.port=6660

# Fix for the Config Server Error
spring.cloud.config.enabled=false

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.client.service-url.defaultZone=http://localhost:6660/eureka/
